config/routes.rb
ThreeTwoThree::Application.routes.draw do

    get "account/index"
    get "account/join"
    get "account/login"
    get "account/logout"
    get "account/send_message_to_selected"
    get "account/signup"
    match  'account/signup_action', :controller => 'account', :action => 'signup_action'
    match  'account/edit_password', :controller => 'account', :action => 'edit_password'
    match "account/forgot_password", :controller => 'account', :action => 'forgot_password'
    match "account/reset_password/:id", :controller => 'account', :action => 'reset_password'
    match "account/reset_password", :controller => 'account', :action => 'reset_password'
    match "account/reset_link_was_sent", :controller => 'account', :action => 'reset_link_was_sent'
    match 'account/login', :controller => 'account', :action => 'login'
    match 'account/newsletter_subscriber', :controller => 'account', :action => 'newsletter_subscriber'
    match 'account/wholesale_only_website', :controller => 'account', :action => 'wholesale_only_website'
    match  '/account', :controller => 'account', :action => 'index'

  match "control_sheet/index", :controller => 'control_sheet', :action => 'index'
  match "control_sheet/initiate_index", :controller => 'control_sheet', :action => 'index'
  match "control_sheet/control_js", :controller => 'control_sheet', :action => 'control_js'
  match "control_panels", :controller => 'control_panels', :action => 'index'
  match "control_sheet/work_order_details", :controller => 'control_sheet', :action => 'work_order_details'
  match "control_sheet/edit_purchases_entry_details", :controller => 'control_sheet', :action => 'edit_purchases_entry_details'

  match '/catalogs/website_design_departments_catalog' , :controller => 'catalogs', :action => 'website_design_departments_catalog'
  resources :catalogs
  match '/catalogs/show_catalog/:id' , :controller => 'catalogs', :action => 'show_catalog'

  match '/image_manager/missing_psd_images' , :controller => 'image_manager', :action => 'missing_psd_images'
  match '/image_manager/missing_sublimation_images' , :controller => 'image_manager', :action => 'missing_sublimation_images'
  match '/image_manager/print_all/:purchase_id' , :controller => 'image_manager', :action => 'print_all'
  match '/image_manager/print_big_fronts/:purchase_id' , :controller => 'image_manager', :action => 'print_big_fronts'
  match '/image_manager/print_all_over_ts/:purchase_id' , :controller => 'image_manager', :action => 'print_all_over_ts'
  match '/image_manager/order_details/:purchase_id' , :controller => 'image_manager', :action => 'order_details'
  match '/image_manager' , :controller => 'image_manager', :action => 'index'

  match '/your_purchases_this_year' , :controller => 'customer_item_sales_by_years', :action => 'your_purchases_this_year'

  match "item_reports/designs_by_department", :controller => 'item_reports', :action => 'designs_by_department'
  match 'features/carousel_department/:department_id' , :controller => 'features', :action => 'carousel_department'
  match 'features/carousel/:feature_name' , :controller => 'features', :action => 'carousel'
  match 'features/list/:name' , :controller => 'features', :action => 'list'
  match 'features/:id/destroy/:item_id' , :controller => 'features', :action => 'destroy'
  match 'features/create/' , :controller => 'features', :action => 'create'
  match 'features/update/' , :controller => 'features', :action => 'update'
  match 'features/:id/show/:item_id' , :controller => 'features', :action => 'show'
  match 'features/new/:item_id' , :controller => 'features', :action => 'new'
  match 'features/:id/edit/:item_id' , :controller => 'features', :action => 'edit'
  match 'features/:item_id' , :controller => 'features', :action => 'index'
  match 'features' , :controller => 'features', :action => 'index'

  match "promo/:promo", :to => redirect("/p/new-home")

  match "p/home", :to => 'page#show_page_on_index', :page_id  => 'new-home'

  match "featured_items/list", :to => 'featured_items#list'

  resources :featured_items

  match '*_store/view_details', :controller => 'specsheet', :action => 'index'

  match '/new_designs' , :controller => 'store', :action => 'new_designs'
  match '/sale_designs' , :controller => 'store', :action => 'sale_designs'

  match 'quote_tender_entries/check', :controller => 'quote_tender_entries', :action => 'check'
  match 'quote_tender_entries/credit_card', :controller => 'quote_tender_entries', :action => 'credit_card'
  match 'quote_tender_entries/net_30', :controller => 'quote_tender_entries', :action => 'net_30'
  match 'quote_tender_entries/cod_money_order_cashiers_check', :controller => 'quote_tender_entries', :action => 'cod_money_order_cashiers_check'
  match 'quote_tender_entries/cod_check', :controller => 'quote_tender_entries', :action => 'cod_check'

  match "search/search_type_name/:search_type_name/query/:query", :controller => "search", :action => "index"
  match 'ship_tos/choose_ship_to', :controller => 'ship_tos', :action => 'choose_ship_to'
  match 'ship_tos/shipping_services', :controller => 'ship_tos', :action => 'shipping_services'
  match 'ship_tos/set_shipping_charge_on_order/:shipping_service_id', :controller => 'ship_tos', :action => 'set_shipping_charge_on_order'
  match 'ship_tos/show_chosen', :controller => 'ship_tos', :action => 'show_chosen'
  resources   :ship_tos, :customers, :quote_tender_entries

  constraints(WebsiteRoutingConstraint) do

    match "catalog", :controller => 'item_reports', :action => 'designs_by_department'

    match '/customer_item_sales_by_years' , :controller => 'customer_item_sales_by_years', :action => 'index'

    resources :item_sales,:websites

    get "films/VideoCapture"
    match "/test", :controller => 'test', :action => 'index' #, :constraints => WebsiteRoutingConstraint
    match "films/search", :controller => 'films', :action => 'search'
    match "films/camerasnap", :controller => 'films', :action => 'camerasnap'
    match "films/camerasnap_update", :controller => 'films', :action => 'camerasnap_update'
    resources  :films

  end

  match 'specsheet/crest_prints_list/:main_design_id' => 'specsheet#crest_prints_list'
  match 'specsheet/crest_prints_list' => 'specsheet#crest_prints_list'

  match "specsheet/admin_crest_prints_list/:main_design_id", :controller => "specsheet", :action => "admin_crest_prints_list"
  match "specsheet/update_crest_prints_list", :controller => "specsheet", :action => "update_crest_prints_list"
  match "specsheet/crest_prints_list/:main_design_id", :controller => "specsheet", :action => "crest_prints_list"
  match "specsheet/update_specsheet", :controller => "specsheet", :action => "update_specsheet"
  match "specsheet/update_sublimation_garments", :controller => "specsheet", :action => "update_sublimation_garments"
  match 'store/close_window/' => 'store#close_window'

  match 'specsheet/item/:item_id/design/:design_id' => 'specsheet#index'
  match 'specsheet/:item_id' => 'specsheet#index'
  match 'specsheet/:item_id/:department_id/:category_id' => 'specsheet#index'

  match 'view_details/:item_id/:department_id' => 'specsheet#index'
  match 'view_details'  => 'specsheet#index'

  match "p/delete_static_page_cache/:page_id", :controller => "page", :action => "delete_static_page_cache"
  match "index" => 'page#show_page_on_index', :page_id  => 'new-home'

  match "search/scroll/:department_id/:page", :controller => "search", :action => "scroll"
  match "search/scroll/:department_id", :controller => "search", :action => "scroll"

  match "search/scroll", :controller => "search", :action => "scroll"
  match 'store/category_items_menu' => 'store#category_items_menu'
  match 'store/department_category_list/:department_id/item_type/:item_type/show/:show' => 'store#department_category_list'
  match 'store/ajax_browse' => 'store#ajax_browse'

  match 'store/browse' => 'store#browse'
  match 'store/category_items/:department_id/:category_id' => 'store#category_items'
  match 'store/category_items' => 'store#category_items_menu'
  match 'store/category_items/:department_id/:category_id' => 'store#category_items'
  match 'store/category_items/:department_id' => 'store#category_items'
  match 'store/category_items/' => 'store#category_items'
  match 'store/departments_containing_categories' => 'store#departments_containing_categories'
  match 'store/enlarge/:item_id' => 'store#enlarge'
  match 'store/select_category/:department_id' => 'store#select_category'
  match 'store/select_department' => 'store#select_department'
  match 'store/index' => 'store#category_items'
  match 'store/items_menu' => 'store#items_menu'
  match 'store/jquery_data' => 'store#jquery_data'
  match 'store/design' => 'store#design'
  match 'store/merchandise' => 'store#merchandise'
  match 'store/tshirtsinabox_redirect_choices' => 'store#tshirtsinabox_redirect_choices'
  match 'store/sublimation_explaination' => 'store#sublimation_explaination'
  match 'store/modal' => 'store#modal'
  match 'store/grid' => 'store#grid'
  match 'store/item' => 'store#item'
  match 'store/specsheet/:item_id' => 'store#specsheet'
  match 'store/update_advanced_combination/:id' => 'store#update_advanced_combination'
  match 'store/test' => 'store#test'
  match 'store' => 'store#category_items'
  match 'dixie_store/category_browser' => 'store#category_items'
  match 'dixie_store/browse' => 'store#category_items'
  match 'dixie_store' => 'store#category_items'
  match 'purchases/checkout_receipt', :controller => 'purchases', :action => 'checkout_receipt'
  match 'purchases/checkout_review', :controller => 'purchases', :action => 'checkout_review'
  match 'purchases/complete_order', :controller => 'purchases', :action => 'complete_order'
  match 'purchases/cancel_order', :controller => 'purchases', :action => 'cancel_order'

  resources  :purchases

  match "add_to_cart", :controller => "cart", :action => 'add_to_cart'

app/models/featured_item.rb
class FeaturedItem < ActiveRecord::Base
  attr_accessible :active, :carousel_name, :description, :image_name, :carousel_url, :onclick   , :list_url   , :verbiage, :list
end

app/controllers/featured_items_controller.rb
class FeaturedItemsController < ApplicationController
  before_filter  :initialize_variables
  before_filter :redirect_unless_admin ,:except => :list
  skip_before_filter :verify_authenticity_token , :only => :destroy

  def list
    @featured_items = FeaturedItem.where("website_id = ? and list = ?", @website.id , true  ). all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @featured_items }
    end
  end


  def index
    @featured_items = FeaturedItem.where("website_id = ?", @website.id ). all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @featured_items }
    end
  end

  # GET /featured_items/1
  # GET /featured_items/1.json
  def show
    @featured_item = FeaturedItem.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @featured_item }
    end
  end

  # GET /featured_items/new
  # GET /featured_items/new.json
  def new
    @featured_item = FeaturedItem.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @featured_item }
    end
  end

  # GET /featured_items/1/edit
  def edit
    @featured_item = FeaturedItem.find(params[:id])
  end

  # POST /featured_items
  # POST /featured_items.json
  def create
    @featured_item = FeaturedItem.new(params[:featured_item])
    @featured_item.website_id = @website.id

    respond_to do |format|
      if @featured_item.save
        format.html { redirect_to @featured_item, notice: 'Featured item was successfully created.' }
        format.json { render json: @featured_item, status: :created, location: @featured_item }
      else
        format.html { render action: "new" }
        format.json { render json: @featured_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /featured_items/1
  # PUT /featured_items/1.json
  def update
    @featured_item = FeaturedItem.find(params[:id])

    respond_to do |format|
      if @featured_item.update_attributes(params[:featured_item])
        format.html { redirect_to @featured_item, notice: 'Featured item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @featured_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /featured_items/1
  # DELETE /featured_items/1.json
  def destroy
    @featured_item = FeaturedItem.find(params[:id])
    @featured_item.destroy

    respond_to do |format|
      format.html { redirect_to featured_items_url }
      format.json { head :no_content }
    end
  end
end

app/views/featured_items/_form.html.erb
<%= form_for(@featured_item) do |f| %>
  <% if @featured_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@featured_item.errors.count, "error") %> prohibited this featured_item from being saved:</h2>

      <ul>
      <% @featured_item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :verbiage %><br />
    <%= f.text_area :verbiage %>
  </div>

  <div class="field">
    <%= f.label :list_url %><br />
    <%= f.text_area :list_url %>
  </div>

    <div class="field">
    <%= f.label :carousel_url %><br />
    <%= f.text_area :carousel_url %>
  </div>
    <div class="field">
      <%= f.label :onclick %><br />
      <%= f.text_area :onclick %>
    </div>
  <div class="field">
    <%= f.label :image_name %><br />
    <%= f.text_area :image_name %>
  </div>
  <div class="field">
    <%= f.label :include_in_carousel %>
    <%= f.check_box :active %>
  </div>
    <br>
    <div class="field">
      <%= f.label :include_in_list %>
      <%= f.check_box :list %>
    </div>
     <br>
  <div class="field">
    <%= f.label :carousel_name %><br />
    <%= f.text_field :carousel_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/featured_items/edit.html.erb
<h1>Editing featured_item</h1>

<%= render 'form' %>

<%= link_to 'Show', @featured_item %> |
<%= link_to 'Back', featured_items_path %>

app/views/featured_items/index.html.erb
<h1>Listing Featured Items</h1>

<table>
  <tr>
    <th>Image</th>
    <th>Description</th>
    <th>Verbiage</th>
    <th>Active</th>
    <th>Carousel name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @featured_items.each do |featured_item| %>
  <tr>
    <td><a href="<%= featured_item.list_url %>"><%=  image_tag  "http://cdn.dixieoutfitters.com" + featured_item.image_name, :size => "100x100" %></a> </td>
    <td><%= featured_item.description %></td>
    <td><%= featured_item.verbiage %></td>
    <td><%= featured_item.active %></td>
    <td><%= featured_item.carousel_name %></td>
    <td><%= link_to 'Show', featured_item %></td>
    <td><%= link_to 'Edit', edit_featured_item_path(featured_item) %></td>
    <td><%= link_to 'Destroy', featured_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Featured item', new_featured_item_path %>

app/views/featured_items/list.html.erb
<style type="text/css">


   .ui-listview .ui-li-has-thumb > img:first-child, .ui-listview .ui-li-has-thumb > .ui-btn > img:first-child, .ui-listview .ui-li-has-thumb .ui-li-thumb {
       max-height: 150px;
       max-width: 150px;
   }

   .ui-listview > .ui-li-has-thumb > .ui-btn, .ui-listview > .ui-li-static.ui-li-has-thumb {
        padding-left:150px;
   }

   .ui-listview >  li h2 {
          margin-left: 10px  ;
          margin-right: 10px  ;
          margin-bottom: 0px  ;
          margin-top: 0px  ;
       white-space: normal;
   }

  .list-view  >  li > a.ui-btn {
       padding: 60px;;
   }


</style>





<img alt="" class="float_100" src="http://cdn.dixieoutfitters.com/images/carousel/featured-items-list.gif" />       <br>   <br>
<%#= @featured_items.size %>
<ul data-role="listview" data-inset="true" class="list-view">
              <% @featured_items.each do |featured_item| %>
                          <li>
                                    <a href="<%= featured_item.list_url %>">
                                            <%=  image_tag  "http://cdn.dixieoutfitters.com" + featured_item.image_name %>
                                            <h2><%= featured_item.description %></h2>
                                            <!--<p><%#= featured_item.verbiage %></p>-->
                                    </a>
                          </li>
              <% end %>
</ul>

app/views/featured_items/new.html.erb
<h1>New featured_item</h1>

<%= render 'form' %>

<%= link_to 'Back', featured_items_path %>

app/views/featured_items/show.html.erb
<p id="notice"><%= notice %></p>



<p><%= image_tag  "http://cdn.dixieoutfitters.com" + @featured_item.image_name, :size => "100x100"%> </p>

<p>
  <b>Description:</b>
  <%= @featured_item.description %>
</p>

<p>
  <b>list_url:</b>
  <%= @featured_item.list_url %>
</p>

<p>
  <b>carousel_url:</b>
  <%= @featured_item.carousel_url %>
</p>

<p>
  <b>onclick:</b>
  <%= @featured_item.onclick %>
</p>

<p>
  <b>Image name:</b>
  <%= @featured_item.image_name %>
</p>

<p>
  <b>Include in carousel:</b>
  <%= @featured_item.active %>
</p>

<p>
  <b>Include in List:</b>
  <%= @featured_item.list %>
</p>

<p>
  <b>Carousel name:</b>
  <%= @featured_item.carousel_name %>
</p>


<%= link_to 'Edit', edit_featured_item_path(@featured_item) %> |
<%= link_to 'Back', featured_items_path %>