config/routes.rb
ThreeTwoThree::Application.routes.draw do

    get "account/index"
    get "account/join"
    get "account/login"
    get "account/logout"
    get "account/send_message_to_selected"
    get "account/signup"
    match  'account/signup_action', :controller => 'account', :action => 'signup_action'
    match  'account/edit_password', :controller => 'account', :action => 'edit_password'
    match "account/forgot_password", :controller => 'account', :action => 'forgot_password'
    match "account/reset_password/:id", :controller => 'account', :action => 'reset_password'
    match "account/reset_password", :controller => 'account', :action => 'reset_password'
    match "account/reset_link_was_sent", :controller => 'account', :action => 'reset_link_was_sent'
    match 'account/login', :controller => 'account', :action => 'login'
    match 'account/newsletter_subscriber', :controller => 'account', :action => 'newsletter_subscriber'
    match 'account/wholesale_only_website', :controller => 'account', :action => 'wholesale_only_website'
    match  '/account', :controller => 'account', :action => 'index'

  match "control_sheet/index", :controller => 'control_sheet', :action => 'index'
  match "control_sheet/initiate_index", :controller => 'control_sheet', :action => 'index'
  match "control_sheet/control_js", :controller => 'control_sheet', :action => 'control_js'
  match "control_panels", :controller => 'control_panels', :action => 'index'
  match "control_sheet/work_order_details", :controller => 'control_sheet', :action => 'work_order_details'
  match "control_sheet/edit_purchases_entry_details", :controller => 'control_sheet', :action => 'edit_purchases_entry_details'

  match '/catalogs/website_design_departments_catalog' , :controller => 'catalogs', :action => 'website_design_departments_catalog'
  resources :catalogs
  match '/catalogs/show_catalog/:id' , :controller => 'catalogs', :action => 'show_catalog'

  match '/image_manager/missing_psd_images' , :controller => 'image_manager', :action => 'missing_psd_images'
  match '/image_manager/missing_sublimation_images' , :controller => 'image_manager', :action => 'missing_sublimation_images'
  match '/image_manager/print_all/:purchase_id' , :controller => 'image_manager', :action => 'print_all'
  match '/image_manager/print_big_fronts/:purchase_id' , :controller => 'image_manager', :action => 'print_big_fronts'
  match '/image_manager/print_all_over_ts/:purchase_id' , :controller => 'image_manager', :action => 'print_all_over_ts'
  match '/image_manager/order_details/:purchase_id' , :controller => 'image_manager', :action => 'order_details'
  match '/image_manager' , :controller => 'image_manager', :action => 'index'

  match '/your_purchases_this_year' , :controller => 'customer_item_sales_by_years', :action => 'your_purchases_this_year'

  match "item_reports/designs_by_department", :controller => 'item_reports', :action => 'designs_by_department'
  match 'features/carousel_department/:department_id' , :controller => 'features', :action => 'carousel_department'
  match 'features/carousel/:feature_name' , :controller => 'features', :action => 'carousel'
  match 'features/list/:name' , :controller => 'features', :action => 'list'
  match 'features/:id/destroy/:item_id' , :controller => 'features', :action => 'destroy'
  match 'features/create/' , :controller => 'features', :action => 'create'
  match 'features/update/' , :controller => 'features', :action => 'update'
  match 'features/:id/show/:item_id' , :controller => 'features', :action => 'show'
  match 'features/new/:item_id' , :controller => 'features', :action => 'new'
  match 'features/:id/edit/:item_id' , :controller => 'features', :action => 'edit'
  match 'features/:item_id' , :controller => 'features', :action => 'index'
  match 'features' , :controller => 'features', :action => 'index'

  match "promo/:promo", :to => redirect("/p/new-home")

  match "p/home", :to => 'page#show_page_on_index', :page_id  => 'new-home'

  match "featured_items/list", :to => 'featured_items#list'

  resources :featured_items

  match '*_store/view_details', :controller => 'specsheet', :action => 'index'

  match '/new_designs' , :controller => 'store', :action => 'new_designs'
  match '/sale_designs' , :controller => 'store', :action => 'sale_designs'

  match 'quote_tender_entries/check', :controller => 'quote_tender_entries', :action => 'check'
  match 'quote_tender_entries/credit_card', :controller => 'quote_tender_entries', :action => 'credit_card'
  match 'quote_tender_entries/net_30', :controller => 'quote_tender_entries', :action => 'net_30'
  match 'quote_tender_entries/cod_money_order_cashiers_check', :controller => 'quote_tender_entries', :action => 'cod_money_order_cashiers_check'
  match 'quote_tender_entries/cod_check', :controller => 'quote_tender_entries', :action => 'cod_check'

  match "search/search_type_name/:search_type_name/query/:query", :controller => "search", :action => "index"
  match 'ship_tos/choose_ship_to', :controller => 'ship_tos', :action => 'choose_ship_to'
  match 'ship_tos/shipping_services', :controller => 'ship_tos', :action => 'shipping_services'
  match 'ship_tos/set_shipping_charge_on_order/:shipping_service_id', :controller => 'ship_tos', :action => 'set_shipping_charge_on_order'
  match 'ship_tos/show_chosen', :controller => 'ship_tos', :action => 'show_chosen'
  resources   :ship_tos, :customers, :quote_tender_entries

  constraints(WebsiteRoutingConstraint) do

    match "catalog", :controller => 'item_reports', :action => 'designs_by_department'

    match '/customer_item_sales_by_years' , :controller => 'customer_item_sales_by_years', :action => 'index'

    resources :item_sales,:websites

    get "films/VideoCapture"
    match "/test", :controller => 'test', :action => 'index' #, :constraints => WebsiteRoutingConstraint
    match "films/search", :controller => 'films', :action => 'search'
    match "films/camerasnap", :controller => 'films', :action => 'camerasnap'
    match "films/camerasnap_update", :controller => 'films', :action => 'camerasnap_update'
    resources  :films

  end

  match 'specsheet/crest_prints_list/:main_design_id' => 'specsheet#crest_prints_list'
  match 'specsheet/crest_prints_list' => 'specsheet#crest_prints_list'

  match "specsheet/admin_crest_prints_list/:main_design_id", :controller => "specsheet", :action => "admin_crest_prints_list"
  match "specsheet/update_crest_prints_list", :controller => "specsheet", :action => "update_crest_prints_list"
  match "specsheet/crest_prints_list/:main_design_id", :controller => "specsheet", :action => "crest_prints_list"
  match "specsheet/update_specsheet", :controller => "specsheet", :action => "update_specsheet"
  match "specsheet/update_sublimation_garments", :controller => "specsheet", :action => "update_sublimation_garments"
  match 'store/close_window/' => 'store#close_window'

  match 'specsheet/item/:item_id/design/:design_id' => 'specsheet#index'
  match 'specsheet/:item_id' => 'specsheet#index'
  match 'specsheet/:item_id/:department_id/:category_id' => 'specsheet#index'

  match 'view_details/:item_id/:department_id' => 'specsheet#index'
  match 'view_details'  => 'specsheet#index'

  match "p/delete_static_page_cache/:page_id", :controller => "page", :action => "delete_static_page_cache"
  match "index" => 'page#show_page_on_index', :page_id  => 'new-home'

  match "search/scroll/:department_id/:page", :controller => "search", :action => "scroll"
  match "search/scroll/:department_id", :controller => "search", :action => "scroll"

  match "search/scroll", :controller => "search", :action => "scroll"
  match 'store/category_items_menu' => 'store#category_items_menu'
  match 'store/department_category_list/:department_id/item_type/:item_type/show/:show' => 'store#department_category_list'
  match 'store/ajax_browse' => 'store#ajax_browse'

  match 'store/browse' => 'store#browse'
  match 'store/category_items/:department_id/:category_id' => 'store#category_items'
  match 'store/category_items' => 'store#category_items_menu'
  match 'store/category_items/:department_id/:category_id' => 'store#category_items'
  match 'store/category_items/:department_id' => 'store#category_items'
  match 'store/category_items/' => 'store#category_items'
  match 'store/departments_containing_categories' => 'store#departments_containing_categories'
  match 'store/enlarge/:item_id' => 'store#enlarge'
  match 'store/select_category/:department_id' => 'store#select_category'
  match 'store/select_department' => 'store#select_department'
  match 'store/index' => 'store#category_items'
  match 'store/items_menu' => 'store#items_menu'
  match 'store/jquery_data' => 'store#jquery_data'
  match 'store/design' => 'store#design'
  match 'store/merchandise' => 'store#merchandise'
  match 'store/tshirtsinabox_redirect_choices' => 'store#tshirtsinabox_redirect_choices'
  match 'store/sublimation_explaination' => 'store#sublimation_explaination'
  match 'store/modal' => 'store#modal'
  match 'store/grid' => 'store#grid'
  match 'store/item' => 'store#item'
  match 'store/specsheet/:item_id' => 'store#specsheet'
  match 'store/update_advanced_combination/:id' => 'store#update_advanced_combination'
  match 'store/test' => 'store#test'
  match 'store' => 'store#category_items'
  match 'dixie_store/category_browser' => 'store#category_items'
  match 'dixie_store/browse' => 'store#category_items'
  match 'dixie_store' => 'store#category_items'
  match 'purchases/checkout_receipt', :controller => 'purchases', :action => 'checkout_receipt'
  match 'purchases/checkout_review', :controller => 'purchases', :action => 'checkout_review'
  match 'purchases/complete_order', :controller => 'purchases', :action => 'complete_order'
  match 'purchases/cancel_order', :controller => 'purchases', :action => 'cancel_order'

  resources  :purchases

  match "add_to_cart", :controller => "cart", :action => 'add_to_cart'

app/models/report.rb
class Report < ActiveRecord::Base
  attr_accessible :name, :link   , :description



end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController


ssl_exceptions
before_filter :redirect_unless_manager
before_filter :initialize_variables

######################################################################################
def item_commission_details
		@item = Item.find params[:item_id]
		@begin_date = Date.parse params[:begin_date]
		@end_date = Date.parse  params[:end_date]
		@sales_entries = @item.sales_entry_records(@begin_date,@end_date)
		@total_sales_at_commissioned_price = 0.0
		@total_commissions_at_commissioned_price = 0.0
	  	if @sales_entries  
					  @sales_entries.each do |se|
					  			@total_sales_at_commissioned_price                +=    se.extended_total_at_commissioned_price
								@total_commissions_at_commissioned_price   +=    se.combined_total 
						end
		end
		
end
######################################################################################
def show_commissions_printable
		show_commissions
		  render(:partial => "reports/show_commissions", :layout => 'printable')
end
######################################################################################
def show_commissions
		session[:year_difference] ||= 0
		if  params[:year_difference].class == String
				if  params[:year_difference]  !=  0
				session[:year_difference]  += params[:year_difference].to_f
				end	
		end
		
		@year_difference = session[:year_difference]	
		
		find_quarters(session[:year_difference])                 # lib/startup_dates.rb
		case params[:quarter]
			when '1'
				@begin_date = @first_quarter_begin
				@end_date = @first_quarter_end
			when '2'
				@begin_date = @second_quarter_begin
				@end_date = @second_quarter_end
			when '3'
				@begin_date = @third_quarter_begin
				@end_date = @third_quarter_end
			when '4'
				@begin_date = @fourth_quarter_begin
				@end_date = @fourth_quarter_end
			else
				@begin_date = @first_quarter_begin
				@end_date = @first_quarter_end
		end

		 @commissioned_artist = Customer.find params[:customer_id]
		 @cids = []
		 @customer_items = CustomerItem.find_all_by_customer_id(params[:customer_id]) 
		  @customer_items.each do |ci|
		  		@cids << ci.item_id.to_s if ci.item_id 
		 end if @customer_items
		 conditions = [ "id in (?)", @cids  ]
		 @commissioned_items = Item.find(:all ,  :conditions => conditions, :order => "ItemLookupCode ASC" ) if @cids
		  @items = Item.find(:all  , :limit => 10 )
		  @total_commission = 0.0
			if @commissioned_items  
					  @commissioned_items.each do |item|
					  			@total_commission +=  item.commission_in_dollars(@begin_date,@end_date) 
						end
			end 
			 render(:partial => "reports/show_commissions", :layout => 'reports')  unless action_name == 'show_commissions_printable'
end
######################################################################################
def delete_commissioned_item
		if  params[:item_id]
						@customer_item = CustomerItem.find_by_item_id(params[:item_id])
						if @customer_item 
								@customer_item.destroy
								flash[:notice] = "Item Deleted."
						else
								flash[:notice] = "Item Not found."
						end
			else
						flash[:notice] = "Missing Params."
			end
			redirect_to :back
end
######################################################################################
def add_to_commission_items
		if params[:customer_id] and params[:item_id]
						@item = Item.find(params[:item_id])
						@customer_item = CustomerItem.find_by_item_id(params[:item_id])
						if @customer_item 
								flash[:notice] = "This Item is already on an artists Commisions. You may use RMS to change it, but not from this program."
						else
								@cs = CustomerItem.new
								@cs.customer_id = params[:customer_id]
								@cs.item_id = params[:item_id]
								@cs.save
						end
			else
						flash[:notice] = "Missing Params."
			end
			redirect_to :back
end
######################################################################################
def find_item
		@commissioned_artist = Customer.find params[:customer_id]
		@items = Item.find(:all, :conditions => ["ItemLookupCode LIKE  ?", "%#{params[:item_keywords]}%" ], :limit => 50  )
		render :partial => "reports/item", :collection => @items, :spacer_template => "page_divider"
end
######################################################################################
def commissions
		@commisioned_artists = Customer.commisioned_artists	
end
######################################################################################
  def index
    @reports = Report.find(:all)

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @reports }
    end
  end

  # GET /reports/1
  # GET /reports/1.xml
  def show
    @report = Report.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @report }
    end
  end

  # GET /reports/new
  # GET /reports/new.xml
  def new
    @report = Report.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @report }
    end
  end

  # GET /reports/1/edit
  def edit
    @report = Report.find(params[:id])
  end

  # POST /reports
  # POST /reports.xml
  def create
    @report = Report.new(params[:report])

    respond_to do |format|
      if @report.save
        flash[:notice] = 'Report was successfully created.'
        format.html { redirect_to(@report) }
        format.xml  { render :xml => @report, :status => :created, :location => @report }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @report.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /reports/1
  # PUT /reports/1.xml
  def update
    @report = Report.find(params[:id])

    respond_to do |format|
      if @report.update_attributes(params[:report])
        flash[:notice] = 'Report was successfully updated.'
        format.html { redirect_to(@report) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @report.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /reports/1
  # DELETE /reports/1.xml
  def destroy
    @report = Report.find(params[:id])
    @report.destroy

    respond_to do |format|
      format.html { redirect_to(reports_url) }
      format.xml  { head :ok }
    end
  end
end

app/views/reports/_find_items.erb
Search for Items to add:	
<%  form_remote_tag :url => 'add_to_cart'  do %>
		<%=    text_field_tag  "item_keywords"  %>
		<%= observe_field :item_keywords, :frequency => 7, :update => 'item_rows',  :url => { :action => 'find_item' ,:customer_id =>  @commissioned_artist.id } ,  :with => 'item_keywords'  %>
<% end %>



<div style="border:solid black 1px;float:left;padding:5px;margin:5px;width:100%;">
	
	<table>
		<tbody>
		<tr>
	  		<td> 
	  		<div id="item_rows">
	  		<%= render :partial => "/reports/item", :collection => @items %> 
	  		</div>
	  		</td>
	  	</tr>	
		</tbody>
		</table>


</div>

app/views/reports/_item.erb
	  <div class="item_list_thumbnail_container_admin" style="padding:15px;width:150px;height:250px;overflow:hidden;float:left;background-color:white;">
	    
			<%=   image_tag( item.image_url(  item.default_master_department_id , 'item_thumbnails/','x' ),:border => 0, :size =>"120x120"   )  -%><br /> 
			<%=  item.ItemLookupCode -%><br />
			Size-Color:<%= item.SubDescription1 %><br />
			Terms Found:<%= item.SubDescription3 %><br />
			<%=  item.Description -%><br />
			<%=  item.category.Name -%><br />
			<%= link_to "Add to Commision Items", :controller => "reports", :action => "add_to_commission_items", :customer_id => @commissioned_artist , :item_id => item.id %><br />
		</div>
 

app/views/reports/_quarter_totals.erb
	  <div class="item_list_thumbnail_container_admin" style="padding:15px;width:150px;height:250px;overflow:hidden;float:left;background-color:white;">
	    
			<%=   image_tag( item.image_url(  item.default_master_department_id , 'item_thumbnails/','x' ),:border => 0, :size =>"120x120"   )  -%><br /> 
			<%=  item.ItemLookupCode -%><br />
			Size-Color:<%= item.SubDescription1 %><br />
			Terms Found:<%= item.SubDescription3 %><br />
			<%=  item.Description -%><br />
			<%=  item.category.Name -%><br />
			<%= link_to "Add to Commision Items", :controller => "reports", :action => "add_to_commission_items", :customer_id => @commissioned_artist , :item_id => item.id %><br />
		</div>
 

app/views/reports/_show_commissions.erb
<h1>Listing Commisisons for <%=h @commissioned_artist.FirstName + ' '  +  @commissioned_artist.LastName  %> - <%= link_to 'Back to Commissions list', :controller => "reports", :action => "commissions"  %></h1>
<h3>Be VERY careful the Dates are correct when you Print! - They will change if you are not careful! <h3>
<%= link_to image_tag("/images/buttons/view-printable-format.jpg",:border => '0'), :controller => "reports", :action => "show_commissions_printable" , :quarter => params[:quarter] , :customer_id => @commissioned_artist.id  unless controller.action_name == 'show_commissions_printable' %>


<% originating_action = controller.action_name %>

<h3>Please choose the Year:</h3>
Current Year: <%= @begin_date.year %><br />
Change Year: 
<%= link_to "Add a year", :controller => "reports", :action => originating_action , :quarter => params[:quarter] ,:year_difference => 1  ,:customer_id => @commissioned_artist.id   %> | 
<%= link_to "Subtract a year", :controller => "reports", :action =>  originating_action , :quarter => params[:quarter] ,:year_difference => -1   ,:customer_id => @commissioned_artist.id %>

<br />Year difference :<%= @year_difference  %><br />


<h3>Please choose the Quarter:</h3>
<%= link_to "January-March", :controller => "reports", :action => originating_action, :quarter => "1",:customer_id => @commissioned_artist.id   %> | 
<%= link_to "April-June", :controller => "reports", :action => originating_action , :quarter => "2" ,:customer_id => @commissioned_artist.id  %> | 
<%= link_to "July-September", :controller => "reports", :action => originating_action , :quarter => "3",:customer_id => @commissioned_artist.id   %> | 
<%= link_to "October-December", :controller => "reports", :action => originating_action , :quarter => "4" ,:customer_id => @commissioned_artist.id  %>
<br /><br />

<% params[:quarter]  ||= 1 %> 
	
Quarter Chosen: <%=  params[:quarter]  %> <br />
Begin Date:<%= @begin_date.utc %><br />
End Date:<%= @end_date.utc %><br /> 

<h3>Items in this Artists Commissions:</h3>



<table>
	  <tr>
	    <th>Item</th>
	    <th>Description</th>
	     <th>Fixed Amount</th>
	      <th>Percent of Sale </th>
	      <th>Quantity Sold </th>
	      <th>Quantity Returned </th>
	       <th>Commissionable Qty </th>
	       <th>Total Sales (Commissionable Dollars Sold) </th>
	       <th>Commission </th>
	      
	  </tr>
	  <% if @commissioned_items %>
				  <% @commissioned_items.each do |item| %>
							  <tr>
							    <td><%=h item.ItemLookupCode %></td>
							    <td><%=h item.Description %></td>
							    <td><%=h item.CommissionAmount %></td>  
							    <td><%=h item.CommissionPercentSale %></td>  
							    <td><%= item.quantity_sold(@begin_date,@end_date)  %></td>  
							    <td><%= item.quantity_returned(@begin_date,@end_date)  %></td>  
							     <td><%= item.commissionable_quantity(@begin_date,@end_date)  %></td>  
							     
							     <td><%= item.commissionable_dollars_sold(@begin_date,@end_date)  %></td>  
							     
							     <td><%= item.commission_in_dollars(@begin_date,@end_date)  %></td>   
							     <td><%= link_to "Delete" ,{ :controller => "reports", :action => "delete_commissioned_item" , :item_id => item.id } , :confirm => 'Are you sure?' unless controller.action_name == 'show_commissions_printable'   %></td>     
							      <td><%= link_to "Details", :controller => "reports", :action => "item_commission_details" , :item_id => item.id , :begin_date => @begin_date,  :end_date => @end_date    unless controller.action_name == 'show_commissions_printable'  %></td>     
							  </tr>
					<% end %>
		<% else %>	  
			 		<tr><td>No Items Assigned to this Artist</td></tr>
	 	<% end %>
</table>

<br /><br />

<h3>Totals for Quarter <%= params[:quarter] %> </h3>
<%= @total_commission %>

<br /><br /><br /><br />

<%   unless action_name == 'show_commissions_printable' %>
		<h3> Add items to this Artists Commisions </h3>
		<%= render :partial => "reports/find_items" %>
<% end %> 	
	 	

app/views/reports/commissions.html.erb
<h1>Listing Commisions</h1>

<table>
  <tr>
    <th>AccountNumber</th>
    <th>LastName</th>
    <th>FirstName</th>
     <th>Email</th>
  </tr>

<% @commisioned_artists.each do |artist|  %>
  <tr>
    <td><%=h artist.AccountNumber  %></td>
    <td><%=h artist.LastName %></td>
    <td><%=h artist.FirstName %></td>
    <td><%=h artist.EmailAddress %></td>
     <td><%= link_to 'Show', :controller => "reports", :action => "show_commissions", :customer_id => artist.id  %></td>
  </tr>
  
  
  
  
  
  
  
<% end %>
</table>

<br />

<%= link_to 'Back', reports_path %>

app/views/reports/edit.html.erb
<h1>Editing report</h1>


<%= errors_for(@report, "Opps, unable to edit report").html_safe if @report %>

<%= form_for(@report) do |f| %>

  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
    <p>
    <%= f.label :link %><br />
    <%= f.text_field :link %>
  </p>
  <p>
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.submit "Update" %>
  </p>
<% end %>

<%= link_to 'Show', @report %> |
<%= link_to 'Back', reports_path %>

app/views/reports/index.html.erb
<h1>Listing reports</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
     <th>Link</th>
  </tr>

<% for report in @reports %>
  <tr>
    <td><%=h report.name %></td>
    <td><%=h report.description %></td>
     <td><%= link_to "VIEW REPORT",  report.link %></td>
    <td><%= link_to 'Show', report %></td>
    <td><%= link_to 'Edit', edit_report_path(report) %></td>
    <td><%= link_to 'Destroy', report, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New report', new_report_path %>

app/views/reports/item_commission_details.erb
<h1>Listing Commisions for <%=h @item.ItemLookupCode  %> -  <%=h @item.Description  %></h1>

&nbsp; <strong><%= link_to "Back", :controller => "reports", :action => "commissions"  %></strong><br /><br />

Begin Date:<%= @begin_date %><br />
End Date:<%= @end_date %><br /> 

<h3>Item Sales Entry Breakdown:</h3>



<table>
	  <tr>
	    <th>Time</th>
	    <th>Sale #</th>
	    <th>Customer FirstName</th>
	    <th>Customer LastName</th>
	      <th>Quantity  </th>
	     <th>Actual Price</th>
	     <th>Commissioned Price</th>
	      <th>Total at Commissioned Price</th>
	     <th> Fixed Amount</th>
	     <th>Percent of Sale (%)</th>
	      <th>Fixed Total</th>
	       <th>Percent Total </th>
	        <th>Combined Total </th>

	  </tr>

	  <% if @sales_entries %>
	  

				  <% @sales_entries.each do |se| %>
							  <tr>
							    <td style="width:200px;"><%=h se.sale.sale_time %></td>
							    <td style="width:100px;"><%=h se.sale.customer.FirstName if se.sale.customer %></td>
							     <td style="width:100px;"><%=h se.sale.customer.LastName if se.sale.customer %></td>
							      <td style="width:100px;"><%=h se.sale.id %></td>
							     <td style="width:100px;"><%=h se.Quantity %></td> 
							    <td style="width:100px;"><%=h se.Price %></td> 
							    <td style="width:100px;"><%=h se.commissioned_price  %></td> 
							    <td style="width:100px;"><%=h se.extended_total_at_commissioned_price  %></td> 
							    <td style="width:100px;"><%=h se.item.CommissionAmount %></td> 
							    <td style="width:100px;"><%=h se.item.CommissionPercentSale %></td> 
							     <td style="width:100px;"><%=h se.fixed_total %></td> 
							      <td style="width:100px;"><%=h se.percent_total  %></td>
							          <td style="width:100px;"><%=h se.combined_total %></td>
							  </tr>
					<% end %>
		<% else %>	  
			 		<tr><td>No Sales for this item in this Time Period</td></tr>
	 	<% end %>
</table>



<h3>Total Sales at Commissioned Price: <%= @total_sales_at_commissioned_price %></h3>

<h3>Total Commissions at Commissioned Price:<%= @total_commissions_at_commissioned_price %></h3>

app/views/reports/new.html.erb
<h1>New report</h1>


<%= errors_for(@report, "Opps, unable to edit report").html_safe if @report %>

<%= form_for(@report) do |f| %>


  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
    <p>
    <%= f.label :link %><br />
    <%= f.text_field :link %>
  </p>
  <p>
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.submit "Create" %>
  </p>
<% end %>

<%= link_to 'Back', reports_path %>

app/views/reports/show.html.erb
<p>
  <b>Name:</b>
  <%=h @report.name %>
</p>

<p>
  <b>Description:</b>
  <%=h @report.description %>
</p>

<p>
  <b>Link:</b>
  <%=h @report.link %>
</p>

<%= link_to 'Edit', edit_report_path(@report) %> |
<%= link_to 'Back', reports_path %>